# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1451b33c417d8bb5b3aefdee646dff21aa3611071913475a46c32ed7c3aa7e6b3eb6d059dba485e2ddad3db1e50013c5398db81997e583ce1932cbfe6bf67173

test:
  secret_key_base: ab964f15fc83a446e4ff9100877b6d3f9171227b18478dd3c5e6d62bd471ca5b6d7b7a0c0f45d17300940f055e6c0d9f3929e23432a3e376c98ad00bd236b217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
